### ISSUE TITLE
Message clocks should be automatically converted to immutable maps

### ISSUE THREAD

**Issue by Flaque** [getroomservice/manymerge#2]
If you send a message over the network, it's generally converted to and from JSON, which means you might do something like this:

```ts
network.on("msg-event", data => {
  const msg = JSON.parse(data)
  peer.applyMessage(msg, myDoc);
}) 
```

This will break, since `msg.clock` is not an immutable object. The workaround right now is to manually do something like this:
```ts
import { Map } from 'immutable'; 

// ...

const msg = JSON.parse(data)
msg.clock = Map(msg.clock) // Manually convert JSON to Immutable
peer.applyMessage(msg, myDoc)
```

But this is such a common use case, we should just handle this automatically.

**Comment by skokenes** [comment]
Yes this burned me as I mentioned to you on Slack :)

Automerge.Connection does handle this conversion automatically.

In manymerge, I think the change is as simple as going from, for example, this:
```javascript
// 0. We should immediately update the clock of our peer.
    this._theirClocks = this._theirClocks.set(peerId, msg.clock);
```

to something like this:
```javascript
// 0. We should immediately update the clock of our peer.
    this._theirClocks = this._theirClocks.set(peerId, fromJS(msg.clock));
```

I will try to put a PR together for it
